### ISSUE TITLE
Repair pilot CV broken by m2m flights to categories

### ISSUE THREAD

**Issue by wbreeze** [wbreeze/iaccdb#134]
The pilot CV's at, for example https://iaccdb.iac.org/pilots/2757 are broken due to attempting to reference a singular category vs. multiple categories related to flight records. This is a loose end that was overlooked in #129  It was overlooked primarily because there aren't tests for it. Add tests for it.

**Comment by djmolny** [comment]
Sorry about the duplicate. I skimmed the open issues before submitting, but didn't make the connection.
