### ISSUE TITLE
"POST contests" lacks 'start' date validation, causing a crash

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#44]
The validations in models/contest.rb doesn't check for the presence of the 'start' field. Thus it's possible to POST a new contest with a null start date. This, in turn, causes the application to crash when displaying the home page (https://iaccdb.iac.org) because the date sort bombs when presented with the null value.

Requested solution: validate presence of "start", and ensure that its value is reasonable -- e.g., >= Jan. 1 of the current year.

**Comment by wbreeze** [comment]
Closed with PR #46
