### ISSUE TITLE
Primary tab is blank when first viewing Judge leaders

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#67]
To reproduce:
- Navigate to https://iaccdb.iac.org/leaders/judges
- Observe that the Primary Power tab is active but no results are displayed
- Click on any other tab and observe that results appear
- Click on the Primary tab and observe that results appear

Note that this phenomenon occurs regardless of the year selected.

**Comment by wbreeze** [comment]
Currently all tabs are blank.

I think this is an upgrade to Foundation breaking things issue. Will have a look.

**Comment by wbreeze** [comment]
Repaired with merge of PR #84 and deployed.
