### ISSUE TITLE
Merge assists for Stephen De La Cruz

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#71]
Steve has two sets of assist records: https://iaccdb.iac.org/assistants/719 and https://iaccdb.iac.org/assistants/2577.

**Comment by wbreeze** [comment]
Used the member merge feature in the admin panel to merge the three records we had for Stephen. We had a record with first name, "Stephen De La" and last name "Cruz". Another, the one merged to, had first name Stephen and last name "De La Cruz". A third had first name "Stephan".

You will now get "not found" on the first link and the full data on the second.

I didn't look for name break-up logic to see if we are splitting the name incorrectly somewhere. If this reoccurs, I'll have to do that.
