### ISSUE TITLE
"POST contests.json" fails because IACCDB's Contest object validations are stricter than www.iac.org

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#72]
When a new Contest node is created on www.iac.org, Drupal POSTs a request to iaccdb.iac.org, which should create and return a new Contest object that includes the contest ID #. If Rails validation fails, there's no listing on iaccdb.iac.org and Drupal can't populate the `iaccdb_id` data field.

Here are the ActiveRecord validations for Contest:
`  validates :name, :length => { :in => 4..48 }
  validates :city, :length => { :maximum => 24 }
  validates :state, :length => { :maximum => 2 }
  validates :director, :length => { :maximum => 48 }
  validates :region, :length => { :maximum => 16 }
  validates_presence_of :start`

By contrast, the Drupal site allows any of those string attributes to be up to 255 characters. (The start date _is_ required on www.iac.org.)

Potential fixes:
1. Remove the field length limitations in IACCDB. If this would mess up display formatting, you could use the Rails `truncate` method in the views.
2. Configure the same field length limitations in Drupal.
3. Truncate the strings in Drupal when generating the `POST https://iaccdb.iac.org/contests.json` request.

**Comment by wbreeze** [comment]
Prefer raising the level of validation in the IAC.org forms vs. lowering it here. These length limitations help keep garbage out, or at least limit the length of the garbage.
- What contest name wanted more than 48 characters?
- What city name has more than 24 characters?
- Is it unreasonable to keep state abbreviation to 2 characters? These are U.S. and Canada.
- What contest director has a name with more than 48 characters?
- Region names are from a fixed set, none of which exceeds 16 characters.

**Comment by djmolny** [comment]
After getting bitten by the 48-char limit yet again ("2018 US National Aerobatic Championships - Gliders" = 50 chars), I've instituted limits on the www.iac.org data entry form that mirror the _current_ validation limits in `app/models/contest.rb`, viz:

`  validates :name, :length => { :in => 4..48 }
  validates :city, :length => { :maximum => 24 }
  validates :state, :length => { :maximum => 2 }
  validates :director, :length => { :maximum => 48 }
  validates :region, :length => { :maximum => 16 }`

Since this is most decidedly un-DRY, please endeavour to let me know if/when any validations are added or changed.

**Comment by wbreeze** [comment]
Sorry. Sure. Will do. Understanding the pain. We have a bunch of cases in another app I work on where there's both front-end and back-end validation. One solution I've seen is to have a socket open that the front-end uses to get validation from the back (middle). The other way is this way: ensure front-end validations are stronger or as strong as those in the back.

Of course, we've always disagreed about the selected arbitrary number 48. In this case, "2018" is redundant to the contest date. The "- glider" thing? I've always thought of that as a kludge.
