### ISSUE TITLE
Northwest regional series now requires participation in 3 contests

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#78]
Per a recent change to the P&P, pilots who enter the Regional Series in the Northwest region now need to fly three contests -- just like everyone else.

The `required_contest_count` method in app/services/iac/regional_series.rb needs to be updated accordingly.

**Comment by wbreeze** [comment]
And a date gate set.

**Comment by wbreeze** [comment]
This was solved by the merge and deployment of PR #79
