### ISSUE TITLE
Incorporate 2016 U.S. Nationals results

### ISSUE THREAD

**Issue by wbreeze** [wbreeze/iaccdb#8]
These require import from the ACRO scoring system in use at the Nationals over our own IAC JaSPer system that feeds results directly.

**Comment by djmolny** [comment]
Don't you mean the *ACRO* scoring system?

**Comment by wbreeze** [comment]
Corrected. Thanks.

**Comment by wbreeze** [comment]
Nationals 2016 results are now in the database.  The import recipe is up to date.
